# SITE CONFIGURATION
baseurl: "/ozmanda.github.io"                          # the subpath of your site, e.g. /blog
url: "https://ozmanda.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Julia Usher                                    # site's title
description: "A personal blog - by Julia Usher"      # used by search engines
avatar: assets/img/Julia/julia.png                         # Empty for no avatar in navbar
favicon: assets/img/Julia/julia.png                             # Icon displayed in the tab

# Header and footer text
header_text: Personal Blog  # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg
header_feature_image_responsive: true
footer_text: >
  A member of the <a href="https://cyberneticlearningsystems.github.io/">Cybernetics Learning Systems</a> research unit at the <a href="https://www.zhaw.ch/en/engineering/institutes-centres/cai/"> Centre for Artificial Intelligence</a> at the <a href="https://www.zhaw.ch/en/engineering/">Zurich University of Applied Sciences</a>. <br>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

# Comments options
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 15
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
